name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/arm64, linux/amd64,

    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: uxsoft
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Image
      uses: docker/build-push-action@v6
      with:
         tags: uxsoft/rust-leptos:latest, uxsoft/rust-leptos:${{ github.run_number }}
         platforms: linux/amd64, linux/arm64
         push: true
